import requests


table_name = 'campaign_daily_report'
field_name = 'platform'
value = 'android'
app_name = 'Genius_G'
reportId = "572a13f3-6c1a-4270-9ecc-06860d004953"
exportId = "Mi9CbG9iSWRWMi03Mjc4ZjcxNC04MTgwLTQ0NjAtODE2YS04ZDAwMTY2ZjEzM2ZsY1YzZTFEV0pHTUE4MEZ6NlFQNTJ5QzZqU00ySEx5S3NxUzRjdDFvSkVnPS4="


def main():

    # 设置请求的 URL

    url = f"https://api.powerbi.com/v1.0/myorg/reports/{reportId}/ExportTo"
    # 设置请求头，包括授权信息, filter信息
    headers = {
        "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InoxcnNZSEhKOS04bWdndDRIc1p1OEJLa0JQdyIsImtpZCI6InoxcnNZSEhKOS04bWdndDRIc1p1OEJLa0JQdyJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvYWE1ODIyZjUtODk4ZS00MzEwLTkyYmItNTY0ODg1MGJhMGUyLyIsImlhdCI6MTczNzAxNDE5MCwibmJmIjoxNzM3MDE0MTkwLCJleHAiOjE3MzcwMTk1MjcsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84WkFBQUFQeFc4ZkMrdHBFQkFuNkJmTXBjK0JleFFXZ242anRuZkpwOFZsYmVZQ2k2SGZmSDdvL3BUaTNwNHcyTzNsc3ZsNHpGaDRIZ2ZsMHdaY2Y5WnhzaE5hZkZwNVdFaGtUbk5ZUllQbXczWEIvTT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMThmYmNhMTYtMjIyNC00NWY2LTg1YjAtZjdiZjJiMzliM2YzIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJaaG91IiwiZ2l2ZW5fbmFtZSI6Ik5pbmciLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxMDMuMTAwLjY0LjEyMiIsIm5hbWUiOiJOaW5nIFpob3UiLCJvaWQiOiJhZjZlNWNlMi1mNGE5LTQ3YTUtYjkwNS00OWFkYWUwYzc5Y2YiLCJwdWlkIjoiMTAwMzIwMDA3QzJBNzA2OSIsInJoIjoiMS5BVWtBOVNKWXFvNkpFRU9TdTFaSWhRdWc0Z2tBQUFBQUFBQUF3QUFBQUFBQUFBQW9BWE5KQUEuIiwic2NwIjoiQXBwLlJlYWQuQWxsIENhcGFjaXR5LlJlYWQuQWxsIENhcGFjaXR5LlJlYWRXcml0ZS5BbGwgQ29ubmVjdGlvbi5SZWFkLkFsbCBDb25uZWN0aW9uLlJlYWRXcml0ZS5BbGwgQ29udGVudC5DcmVhdGUgRGFzaGJvYXJkLlJlYWQuQWxsIERhc2hib2FyZC5SZWFkV3JpdGUuQWxsIERhdGFmbG93LlJlYWQuQWxsIERhdGFmbG93LlJlYWRXcml0ZS5BbGwgRGF0YXNldC5SZWFkLkFsbCBEYXRhc2V0LlJlYWRXcml0ZS5BbGwgR2F0ZXdheS5SZWFkLkFsbCBHYXRld2F5LlJlYWRXcml0ZS5BbGwgSXRlbS5FeGVjdXRlLkFsbCBJdGVtLkV4dGVybmFsRGF0YVNoYXJlLkFsbCBJdGVtLlJlYWRXcml0ZS5BbGwgSXRlbS5SZXNoYXJlLkFsbCBPbmVMYWtlLlJlYWQuQWxsIE9uZUxha2UuUmVhZFdyaXRlLkFsbCBQaXBlbGluZS5EZXBsb3kgUGlwZWxpbmUuUmVhZC5BbGwgUGlwZWxpbmUuUmVhZFdyaXRlLkFsbCBSZXBvcnQuUmVhZFdyaXRlLkFsbCBSZXBydC5SZWFkLkFsbCBTdG9yYWdlQWNjb3VudC5SZWFkLkFsbCBTdG9yYWdlQWNjb3VudC5SZWFkV3JpdGUuQWxsIFRlbmFudC5SZWFkLkFsbCBUZW5hbnQuUmVhZFdyaXRlLkFsbCBVc2VyU3RhdGUuUmVhZFdyaXRlLkFsbCBXb3Jrc3BhY2UuR2l0Q29tbWl0LkFsbCBXb3Jrc3BhY2UuR2l0VXBkYXRlLkFsbCBXb3Jrc3BhY2UuUmVhZC5BbGwgV29ya3NwYWNlLlJlYWRXcml0ZS5BbGwiLCJzaWduaW5fc3RhdGUiOlsia21zaSJdLCJzdWIiOiIxTEFxck1wUGpaaHlBOGc5WkNQRHpXSzV1dVN4TjVDRnVjYl9vanI4RVFzIiwidGlkIjoiYWE1ODIyZjUtODk4ZS00MzEwLTkyYmItNTY0ODg1MGJhMGUyIiwidW5pcXVlX25hbWUiOiJuaW5nLnpob3VAZXdwLWdyb3VwLmNvbSIsInVwbiI6Im5pbmcuemhvdUBld3AtZ3JvdXAuY29tIiwidXRpIjoicHhITHdxRnFOMEc5RDk5enNZdEdBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19pZHJlbCI6IjEgNCJ9.bg9g6Jjk_brg3LyeGI5wYmeGh7P0qcrOi976QYj2x0-mMmM8qOwHyFM7Be6VLhlsV6qTxiAMVWCH5CE26k856Lt2UvOU_grbeZRvc9gPxgfvhK5ZIYIfElRGR1_x3-8RfoW9a3hSM4Wmw9tIxm5OYDL7YL9YR8T2SWHRu03hhwJ5ZgTFYFTFFodVhmNkmMDUi4zj2I43nwVgtXAGtGJqnz1labKuRXtOFwtuxE0agvuhCSx0ndg7qqecDE1yEeJT9_0AdYtvav7c-jpG4wYYzsqa2DcAkLy2A91s14NjuCmg6hEltU5puBza63ehmFh92hwvVjFhxxs_LfIGUezzVg"
    }
    body = {
        "format": "PDF",
        "powerBIReportConfiguration": {
            "reportLevelFilters": [
                {
                    "filter": f"{table_name}/{field_name} eq '{value}'" + " and " +  f"{table_name}/spend gt 1000"
                }
            ]
        }
    }

    print(body)
    # 发送 GET 请求
    response = requests.post(url, json=body, headers=headers)
    print(response.json())
    resp = response.json()
    exportId = resp["id"]
    print(exportId)


    # 检查请求是否成功
    # if response.status_code == 200:
    #     # 打印响应内容
    #     print(response.json())
    # else:
    #     print(f"请求失败，状态码: {response.status_code}")


    # url = f"https://api.powerbi.com/v1.0/myorg/reports/{reportId}/exports/{exportId}"
    # response = requests.get(url, headers=headers)
    # print(response.json())


def get_status():
    headers = {
        "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InoxcnNZSEhKOS04bWdndDRIc1p1OEJLa0JQdyIsImtpZCI6InoxcnNZSEhKOS04bWdndDRIc1p1OEJLa0JQdyJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvYWE1ODIyZjUtODk4ZS00MzEwLTkyYmItNTY0ODg1MGJhMGUyLyIsImlhdCI6MTczNzAxOTM3NSwibmJmIjoxNzM3MDE5Mzc1LCJleHAiOjE3MzcwMjQyMzMsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84WkFBQUE3YjhlZVRHbE9OREhKNFpxclA2QUJyNzBDQzBNTmVUZlk3TUtpdGdjNnhmclcvVXo2NXQwR0gxNWdBcmZMUWhGQlpHcnY4SElRWVNoaVA4M1ZXSXNjZDN6NW5qZklxTXB4SUpuUXRkVER5Zz0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMThmYmNhMTYtMjIyNC00NWY2LTg1YjAtZjdiZjJiMzliM2YzIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJaaG91IiwiZ2l2ZW5fbmFtZSI6Ik5pbmciLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxMDMuMTAwLjY0LjEyMiIsIm5hbWUiOiJOaW5nIFpob3UiLCJvaWQiOiJhZjZlNWNlMi1mNGE5LTQ3YTUtYjkwNS00OWFkYWUwYzc5Y2YiLCJwdWlkIjoiMTAwMzIwMDA3QzJBNzA2OSIsInJoIjoiMS5BVWtBOVNKWXFvNkpFRU9TdTFaSWhRdWc0Z2tBQUFBQUFBQUF3QUFBQUFBQUFBQW9BWE5KQUEuIiwic2NwIjoiQXBwLlJlYWQuQWxsIENhcGFjaXR5LlJlYWQuQWxsIENhcGFjaXR5LlJlYWRXcml0ZS5BbGwgQ29ubmVjdGlvbi5SZWFkLkFsbCBDb25uZWN0aW9uLlJlYWRXcml0ZS5BbGwgQ29udGVudC5DcmVhdGUgRGFzaGJvYXJkLlJlYWQuQWxsIERhc2hib2FyZC5SZWFkV3JpdGUuQWxsIERhdGFmbG93LlJlYWQuQWxsIERhdGFmbG93LlJlYWRXcml0ZS5BbGwgRGF0YXNldC5SZWFkLkFsbCBEYXRhc2V0LlJlYWRXcml0ZS5BbGwgR2F0ZXdheS5SZWFkLkFsbCBHYXRld2F5LlJlYWRXcml0ZS5BbGwgSXRlbS5FeGVjdXRlLkFsbCBJdGVtLkV4dGVybmFsRGF0YVNoYXJlLkFsbCBJdGVtLlJlYWRXcml0ZS5BbGwgSXRlbS5SZXNoYXJlLkFsbCBPbmVMYWtlLlJlYWQuQWxsIE9uZUxha2UuUmVhZFdyaXRlLkFsbCBQaXBlbGluZS5EZXBsb3kgUGlwZWxpbmUuUmVhZC5BbGwgUGlwZWxpbmUuUmVhZFdyaXRlLkFsbCBSZXBvcnQuUmVhZFdyaXRlLkFsbCBSZXBydC5SZWFkLkFsbCBTdG9yYWdlQWNjb3VudC5SZWFkLkFsbCBTdG9yYWdlQWNjb3VudC5SZWFkV3JpdGUuQWxsIFRlbmFudC5SZWFkLkFsbCBUZW5hbnQuUmVhZFdyaXRlLkFsbCBVc2VyU3RhdGUuUmVhZFdyaXRlLkFsbCBXb3Jrc3BhY2UuR2l0Q29tbWl0LkFsbCBXb3Jrc3BhY2UuR2l0VXBkYXRlLkFsbCBXb3Jrc3BhY2UuUmVhZC5BbGwgV29ya3NwYWNlLlJlYWRXcml0ZS5BbGwiLCJzaWduaW5fc3RhdGUiOlsia21zaSJdLCJzdWIiOiIxTEFxck1wUGpaaHlBOGc5WkNQRHpXSzV1dVN4TjVDRnVjYl9vanI4RVFzIiwidGlkIjoiYWE1ODIyZjUtODk4ZS00MzEwLTkyYmItNTY0ODg1MGJhMGUyIiwidW5pcXVlX25hbWUiOiJuaW5nLnpob3VAZXdwLWdyb3VwLmNvbSIsInVwbiI6Im5pbmcuemhvdUBld3AtZ3JvdXAuY29tIiwidXRpIjoiR2ZSR1VPUFVXVVdSVkc5X1hYdGFBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19pZHJlbCI6IjEgMTQifQ.j6CY0Qu4ftw_eaeJBXAua4NFVqCuInG38_q1FP_DUsj2IKkW6NuknJAStuAHQTgOM31khzEktTNLBcAHt2W4mw9oRDmeflknAilF6mHaPGFvr5_sfSoTbQX42bJ59iYHIHgBTcOKesl12159EdACy-KdLhMGLJCzMWV9DQKJ5IqHtqMoib5-oSTXVx0dvcMmqVRLCV6zFoKaWqrdqBC58tvLTBXKCDER85duRXH3Ghp5UdYS3L_1lvD0weYqE-pOcOfyE6-Z3RPtF5VaSPOd4l3sAAA0Wr3AMcL9qauLRb2mzm3h4subBq4jW3T4NFfIOAAS6z5C_G60pGEWXJW6nA"
    }
    url = f"https://api.powerbi.com/v1.0/myorg/reports/{reportId}/exports/{exportId}"
    response = requests.get(url, headers=headers)
    print(response.json())

def exportToFile():
    headers = {
        "Authorization": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6InoxcnNZSEhKOS04bWdndDRIc1p1OEJLa0JQdyIsImtpZCI6InoxcnNZSEhKOS04bWdndDRIc1p1OEJLa0JQdyJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvYWE1ODIyZjUtODk4ZS00MzEwLTkyYmItNTY0ODg1MGJhMGUyLyIsImlhdCI6MTczNzAxNDE5MCwibmJmIjoxNzM3MDE0MTkwLCJleHAiOjE3MzcwMTk1MjcsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBVlFBcS84WkFBQUFQeFc4ZkMrdHBFQkFuNkJmTXBjK0JleFFXZ242anRuZkpwOFZsYmVZQ2k2SGZmSDdvL3BUaTNwNHcyTzNsc3ZsNHpGaDRIZ2ZsMHdaY2Y5WnhzaE5hZkZwNVdFaGtUbk5ZUllQbXczWEIvTT0iLCJhbXIiOlsicHdkIiwibWZhIl0sImFwcGlkIjoiMThmYmNhMTYtMjIyNC00NWY2LTg1YjAtZjdiZjJiMzliM2YzIiwiYXBwaWRhY3IiOiIwIiwiZmFtaWx5X25hbWUiOiJaaG91IiwiZ2l2ZW5fbmFtZSI6Ik5pbmciLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxMDMuMTAwLjY0LjEyMiIsIm5hbWUiOiJOaW5nIFpob3UiLCJvaWQiOiJhZjZlNWNlMi1mNGE5LTQ3YTUtYjkwNS00OWFkYWUwYzc5Y2YiLCJwdWlkIjoiMTAwMzIwMDA3QzJBNzA2OSIsInJoIjoiMS5BVWtBOVNKWXFvNkpFRU9TdTFaSWhRdWc0Z2tBQUFBQUFBQUF3QUFBQUFBQUFBQW9BWE5KQUEuIiwic2NwIjoiQXBwLlJlYWQuQWxsIENhcGFjaXR5LlJlYWQuQWxsIENhcGFjaXR5LlJlYWRXcml0ZS5BbGwgQ29ubmVjdGlvbi5SZWFkLkFsbCBDb25uZWN0aW9uLlJlYWRXcml0ZS5BbGwgQ29udGVudC5DcmVhdGUgRGFzaGJvYXJkLlJlYWQuQWxsIERhc2hib2FyZC5SZWFkV3JpdGUuQWxsIERhdGFmbG93LlJlYWQuQWxsIERhdGFmbG93LlJlYWRXcml0ZS5BbGwgRGF0YXNldC5SZWFkLkFsbCBEYXRhc2V0LlJlYWRXcml0ZS5BbGwgR2F0ZXdheS5SZWFkLkFsbCBHYXRld2F5LlJlYWRXcml0ZS5BbGwgSXRlbS5FeGVjdXRlLkFsbCBJdGVtLkV4dGVybmFsRGF0YVNoYXJlLkFsbCBJdGVtLlJlYWRXcml0ZS5BbGwgSXRlbS5SZXNoYXJlLkFsbCBPbmVMYWtlLlJlYWQuQWxsIE9uZUxha2UuUmVhZFdyaXRlLkFsbCBQaXBlbGluZS5EZXBsb3kgUGlwZWxpbmUuUmVhZC5BbGwgUGlwZWxpbmUuUmVhZFdyaXRlLkFsbCBSZXBvcnQuUmVhZFdyaXRlLkFsbCBSZXBydC5SZWFkLkFsbCBTdG9yYWdlQWNjb3VudC5SZWFkLkFsbCBTdG9yYWdlQWNjb3VudC5SZWFkV3JpdGUuQWxsIFRlbmFudC5SZWFkLkFsbCBUZW5hbnQuUmVhZFdyaXRlLkFsbCBVc2VyU3RhdGUuUmVhZFdyaXRlLkFsbCBXb3Jrc3BhY2UuR2l0Q29tbWl0LkFsbCBXb3Jrc3BhY2UuR2l0VXBkYXRlLkFsbCBXb3Jrc3BhY2UuUmVhZC5BbGwgV29ya3NwYWNlLlJlYWRXcml0ZS5BbGwiLCJzaWduaW5fc3RhdGUiOlsia21zaSJdLCJzdWIiOiIxTEFxck1wUGpaaHlBOGc5WkNQRHpXSzV1dVN4TjVDRnVjYl9vanI4RVFzIiwidGlkIjoiYWE1ODIyZjUtODk4ZS00MzEwLTkyYmItNTY0ODg1MGJhMGUyIiwidW5pcXVlX25hbWUiOiJuaW5nLnpob3VAZXdwLWdyb3VwLmNvbSIsInVwbiI6Im5pbmcuemhvdUBld3AtZ3JvdXAuY29tIiwidXRpIjoicHhITHdxRnFOMEc5RDk5enNZdEdBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19pZHJlbCI6IjEgNCJ9.bg9g6Jjk_brg3LyeGI5wYmeGh7P0qcrOi976QYj2x0-mMmM8qOwHyFM7Be6VLhlsV6qTxiAMVWCH5CE26k856Lt2UvOU_grbeZRvc9gPxgfvhK5ZIYIfElRGR1_x3-8RfoW9a3hSM4Wmw9tIxm5OYDL7YL9YR8T2SWHRu03hhwJ5ZgTFYFTFFodVhmNkmMDUi4zj2I43nwVgtXAGtGJqnz1labKuRXtOFwtuxE0agvuhCSx0ndg7qqecDE1yEeJT9_0AdYtvav7c-jpG4wYYzsqa2DcAkLy2A91s14NjuCmg6hEltU5puBza63ehmFh92hwvVjFhxxs_LfIGUezzVg"
    }
    url = f"https://api.powerbi.com/v1.0/myorg/reports/{reportId}/exports/{exportId}/file"
    response = requests.get(url, headers=headers)
    # print(response.text)
    content_type = response.headers.get('Content-Type', '')
    print(content_type)
    if 'application/zip' in content_type:
        file_extension = '.zip'
    elif 'application/pdf' in content_type:
        file_extension = '.pdf'
    elif 'image/' in content_type:
        file_extension = '.png'  # 假设是 PNG 图片
    elif 'text/csv' in content_type:
        file_extension = '.csv'
    elif 'text/xml' in content_type:
        file_extension = '.xml'
    else:
        file_extension = '.dat'  #

    file_name = f"/Users/ning.zhou/Desktop/exported_file{file_extension}"

    # 将文件写入磁盘
    with open(file_name, 'wb') as file:
        file.write(response.content)


if __name__ == '__main__':
    # main()
    get_status()
    # exportToFile()